export const LOGGED_IN_SUCCESS_ACTION = "LOGGED_IN_SUCCESS_ACTION";
export const LOGGED_IN_FAILURE_ACTION = "LOGGED_IN_FAILURE_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION";

export const COUNTRIES_FETCH = "COUNTRIES_FETCH";
export const COUNTRY_FILTER_ADD = "COUNTRY_FILTER_ADD";
export const COUNTRY_FILTER_REMOVE = "COUNTRY_FILTER_REMOVE";
export const COUNTRY_FILTER_CLEAR = "COUNTRY_FILTER_CLEAR";
